name: Build and Push ETL Image to DockerHub

on: # trigger
    push:
        branches: [ main ]

    workflow_dispatch: # manual
        
jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: list directory
              run: ls -ltr 
            